language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
# Executed only when pull request on master branch
branches:
  only:
    - master
# Before executing test we need to install dependencies
before_script:
  - npm install
script:
  - npm test
